### ISSUE TITLE
Book name?

### ISSUE THREAD

**Issue by lakshaytalkstomachines** [noissefnoc/book-deep-learning-from-scratch#1]
What Book is this ? Author Name? This is not of Seith Weidman right?

**Comment by noissefnoc** [comment]
> What Book is this ?

"Deep Learning from scratch" (Ja『ゼロから作る Deep Learning』)
https://www.oreilly.co.jp/books/9784873117584/

This repository is my reading log of this book.


>  Author Name? This is not of Seith Weidman right?

The book author is Koki Saito (his facebook is https://www.facebook.com/670403599796194). And this is not of Seith Weidman.

I hope this answers your question.
